name: Calculate Metrics

on:
  # Nightly at midnight UTC (adjust cron as needed)
  schedule:
    - cron:  '0 0 * * *'
  # Manual trigger
  workflow_dispatch:

jobs:
  calculate-metrics:
    runs-on: ubuntu-latest
    env:
      # If you’re using DATABASE_URL:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # Or, if you prefer individual SUPABASE_* vars, comment out the line above and uncomment these:
      # SUPABASE_HOST:     ${{ secrets.SUPABASE_HOST }}
      # SUPABASE_DATABASE: ${{ secrets.SUPABASE_DATABASE }}
      # SUPABASE_USER:     ${{ secrets.SUPABASE_USER }}
      # SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      # SUPABASE_PORT:     ${{ secrets.SUPABASE_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install psycopg2-binary python-dotenv

      - name: Run metrics script
        run: python data_pipeline/calculate_metrics.py
