"""
clean_app_store.py

This script uses Pandas to clean up the initial CSV generated by
scraper_app_store.py.

Order of operations: Drop title series → Add platform col → Write clean CSV

Return: cleaned CSV 'cleaned_app_store.csv'
"""

import pandas as pd

df = pd.read_csv("raw_apple_data.csv")

"""
apple's csv series names:
author_name	rating	review_text	review_date	title	app_version

need to drop title col since google doesn't use that
"""

df = df.drop(["title"], axis=1)

# reorder

df = df[["author_name", 
         "rating", 
         "review_text", 
         "review_date", 
         "app_version"]]

df["platform"] = "apple"

df.to_csv("clean_app_store.csv", index=False)